### PR TITLE
Asynchonous tile fetch

### PR DESCRIPTION
**Pull request by lovasoa**
@JohnDoee @kolt54321 Can you try these changes ? If it works well for you too, then I'll merge it.

### CODE REVIEW

**Comment by kolt54321** [comment]
Will do! At work now but will try when I get home in a few hours.

**Comment by JohnDoee** [comment]
Tested a few images, works fantastic. The downloading part seems to be a lot faster but I assume you mean total time when you said "30%".

**Comment by kolt54321** [comment]
On lower resolutions it works great. I'm hitting an error though ("encoder error -2 when writing image file") when trying to pull Wedding Supper on zoom 8. I know all the tiles downloaded correctly, it's just something with the save function that triggers the error.

I would say it's ~50% faster, at least. It's really good.

**Comment by lovasoa** [comment]
@kolt54321 Is this a new issue specific to the asynchronous tile fetch ? Or did you experience the same issue before ? Maybe the jpeg encoder has issues with very large files, did you try exporting the image to a different format ?

**Comment by kolt54321** [comment]
@lovasoa Sorry! Just ran into computer issues, it might be a bit before I can test again. It's possible png is fine :)

**Comment by lovasoa** [comment]
I am going to merge this. Please comment if you encounter new issues.

**Pull request merged**
